import { UpgradeTier } from '../types';

export const SWORD_UPGRADES: UpgradeTier[] = [
  {
    level: 1,
    name: 'Iron Sword',
    cost: 0,
    statBonus: 15,
    description: 'Basic standard-issue iron blade.',
    color: '#94a3b8',
  },
  {
    level: 2,
    name: 'Steel Sword',
    cost: 100,
    statBonus: 22,
    description: 'Tempered steel forged with higher sharpness.',
    color: '#cbd5e1',
  },
  {
    level: 3,
    name: 'Knight Sword',
    cost: 250,
    statBonus: 32,
    description: 'Heavy broadsword inscribed with kingdom crest.',
    color: '#38bdf8',
  },
  {
    level: 4,
    name: 'Royal Sunblade',
    cost: 500,
    statBonus: 46,
    description: 'Gilded blade radiating golden solar aura.',
    color: '#facc15',
  },
  {
    level: 5,
    name: 'Dragon Slayer',
    cost: 1000,
    statBonus: 65,
    description: 'Legendary obsidian broadsword imbued with dragon flame.',
    color: '#ef4444',
  },
  {
    level: 6,
    name: 'Arcane Cleaver',
    cost: 1600,
    statBonus: 88,
    description: 'Infused with Sorcerer Spire ethereal mana crystals.',
    color: '#c084fc',
  },
  {
    level: 7,
    name: 'Celestial Edge',
    cost: 2400,
    statBonus: 115,
    description: 'Forged from astral meteoric fragments, slices with cosmic force.',
    color: '#38bdf8',
  },
  {
    level: 8,
    name: 'Netherflame Destroyer',
    cost: 3500,
    statBonus: 145,
    description: 'Smelted in the deep magma chasms of the Abyssal realm.',
    color: '#f97316',
  },
  {
    level: 9,
    name: 'Archon Godblade',
    cost: 5000,
    statBonus: 185,
    description: 'Divine relic capable of shattering infernal barriers.',
    color: '#fbbf24',
  },
  {
    level: 10,
    name: 'Omega Blade of Eternity',
    cost: 7500,
    statBonus: 240,
    description: 'Ultimate mythical armament carrying the primordial forces of creation.',
    color: '#ec4899',
  },
];

export const ARMOR_UPGRADES: UpgradeTier[] = [
  {
    level: 1,
    name: 'Iron Armor',
    cost: 0,
    statBonus: 5,
    description: 'Standard chainmail and iron plate cuirass.',
    color: '#64748b',
  },
  {
    level: 2,
    name: 'Reinforced Plate',
    cost: 100,
    statBonus: 10,
    description: 'Double-layered steel plating.',
    color: '#94a3b8',
  },
  {
    level: 3,
    name: "Knight's Hauberk",
    cost: 250,
    statBonus: 16,
    description: 'Custom royal guard armor with Pauldrons.',
    color: '#0284c7',
  },
  {
    level: 4,
    name: 'Champion Aegis',
    cost: 500,
    statBonus: 24,
    description: 'Mithril weave resistant to crushing impacts.',
    color: '#eab308',
  },
  {
    level: 5,
    name: 'Dragon Scale Armor',
    cost: 1000,
    statBonus: 35,
    description: 'Scales of the ancient wyrm, impervious to fire.',
    color: '#dc2626',
  },
  {
    level: 6,
    name: 'Sorcerer Ward Robes',
    cost: 1600,
    statBonus: 48,
    description: 'Enchanted silks that disperse magical projectiles.',
    color: '#a855f7',
  },
  {
    level: 7,
    name: 'Astralis Carapace',
    cost: 2400,
    statBonus: 64,
    description: 'Cosmic alloy that absorbs gravitational kinetic forces.',
    color: '#06b6d4',
  },
  {
    level: 8,
    name: 'Abyssal Nether Cuirass',
    cost: 3500,
    statBonus: 82,
    description: 'Forged from cooled demon obsidian, laughs at hellfire.',
    color: '#b91c1c',
  },
  {
    level: 9,
    name: 'Titan Bastion Plate',
    cost: 5000,
    statBonus: 105,
    description: 'Colossal titan steel capable of withstanding siege catapults.',
    color: '#eab308',
  },
  {
    level: 10,
    name: 'Immortal King Carapace',
    cost: 7500,
    statBonus: 135,
    description: 'Legendary royal regalia providing near-impervious defense.',
    color: '#f43f5e',
  },
];

export const HEALTH_UPGRADES: UpgradeTier[] = [
  {
    level: 1,
    name: 'Vitality I',
    cost: 0,
    statBonus: 100,
    description: 'Base knight constitution (100 HP).',
    color: '#10b981',
  },
  {
    level: 2,
    name: 'Vitality II',
    cost: 100,
    statBonus: 130,
    description: 'Increased maximum health to 130 HP.',
    color: '#34d399',
  },
  {
    level: 3,
    name: 'Vitality III',
    cost: 250,
    statBonus: 165,
    description: 'Increased maximum health to 165 HP.',
    color: '#059669',
  },
  {
    level: 4,
    name: 'Vitality IV',
    cost: 500,
    statBonus: 210,
    description: 'Increased maximum health to 210 HP.',
    color: '#047857',
  },
  {
    level: 5,
    name: 'Vitality V',
    cost: 1000,
    statBonus: 260,
    description: 'Immense vitality peaking at 260 HP.',
    color: '#065f46',
  },
  {
    level: 6,
    name: 'Vitality VI',
    cost: 1600,
    statBonus: 325,
    description: 'Mana-infused bloodline elevating vitality to 325 HP.',
    color: '#0d9488',
  },
  {
    level: 7,
    name: 'Vitality VII',
    cost: 2400,
    statBonus: 400,
    description: 'Astral heart blessing surging health to 400 HP.',
    color: '#0284c7',
  },
  {
    level: 8,
    name: 'Vitality VIII',
    cost: 3500,
    statBonus: 490,
    description: 'Infernal fireblood resilience reaching 490 HP.',
    color: '#ea580c',
  },
  {
    level: 9,
    name: 'Vitality IX',
    cost: 5000,
    statBonus: 590,
    description: 'Demi-god physical constitution reaching 590 HP.',
    color: '#d97706',
  },
  {
    level: 10,
    name: 'Vitality X (Immortal Core)',
    cost: 7500,
    statBonus: 720,
    description: 'Peak mythological life essence boasting 720 HP.',
    color: '#10b981',
  },
];

export const SHIELD_UPGRADES: UpgradeTier[] = [
  {
    level: 1,
    name: 'Wooden Buckler',
    cost: 0,
    statBonus: 15,
    description: 'Basic defense: blocks 15% damage.',
    color: '#b45309',
  },
  {
    level: 2,
    name: 'Iron Roundshield',
    cost: 150,
    statBonus: 25,
    description: 'Sturdy iron rim: blocks 25% damage.',
    color: '#94a3b8',
  },
  {
    level: 3,
    name: 'Kite Shield',
    cost: 350,
    statBonus: 35,
    description: 'Towering defense: blocks 35% damage.',
    color: '#0ea5e9',
  },
  {
    level: 4,
    name: 'Royal Crest Shield',
    cost: 700,
    statBonus: 45,
    description: 'Blessed barricade: blocks 45% damage.',
    color: '#f59e0b',
  },
  {
    level: 5,
    name: 'Dragon Ward',
    cost: 1200,
    statBonus: 55,
    description: 'Impenetrable bulwark: blocks 55% damage.',
    color: '#ef4444',
  },
  {
    level: 6,
    name: 'Arcane Aegis Ward',
    cost: 1800,
    statBonus: 65,
    description: 'Crystal barrier: blocks 65% damage.',
    color: '#c084fc',
  },
  {
    level: 7,
    name: 'Prism Deflector',
    cost: 2600,
    statBonus: 72,
    description: 'Reflective prism surface: blocks 72% damage.',
    color: '#38bdf8',
  },
  {
    level: 8,
    name: 'Abyssal Dreadguard',
    cost: 3800,
    statBonus: 80,
    description: 'Demonic monolith shield: blocks 80% damage.',
    color: '#dc2626',
  },
  {
    level: 9,
    name: 'Celestial Bastion',
    cost: 5400,
    statBonus: 88,
    description: 'Star-forged bulwark: blocks 88% damage.',
    color: '#fbbf24',
  },
  {
    level: 10,
    name: 'Divine Aegis Matrix',
    cost: 8000,
    statBonus: 95,
    description: 'Ultimate fortress barrier: blocks 95% damage.',
    color: '#10b981',
  },
];
